name: Waka Readme

on:
  schedule:
    # Runs every 6 hours instead of every hour for better performance
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
          # Display Options - Only show the most beautiful and relevant sections
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_TIMEZONE: "False"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE: "True"
          SHOW_OS: "False"
          SHOW_PROJECTS: "True"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
          
          # Language and Formatting
          LOCALE: "en"
          SHOW_LINES_OF_CODE: "False"
          SHOW_PROFILE_VIEWS: "False"
          
          # Time range - Show more meaningful data
          SHOW_TOTAL_CODE_TIME: "False" 
